@startuml
!pragma layout elk
skinparam classAttributeIconSize 0
class DecoyDuck {
  display() : void
}
Duck <|-- DecoyDuck
class DecoyFly {
  fly() : void
}
FlyBehavior <|.. DecoyFly
class DecoyQuack {
  quack() : void
}
QuackBehavior <|.. DecoyQuack
class DecoySwim {
  swim() : void
}
SwimBehavior <|.. DecoySwim
class Duck {
  flyBehavior : FlyBehavior
  quackBehavior : QuackBehavior
  swimBehavior : SwimBehavior
  walkBehavior : WalkBehavior
  setFlyBehavior(fb : FlyBehavior) : void
  setQuackBehavior(qb : QuackBehavior) : void
  setSwimBehavior(sb : SwimBehavior) : void
  setWalkBehavior(wb : WalkBehavior) : void
  display() : void
  performFly() : void
  performQuack() : void
  performSwim() : void
  performWalk() : void
}
interface FlyBehavior {
  fly() : void
}
class Main {
  main(args : String[]) : void
}
class MallardDuck {
  display() : void
}
Duck <|-- MallardDuck
class MallardFly {
  fly() : void
}
FlyBehavior <|.. MallardFly
class MallardQuack {
  quack() : void
}
QuackBehavior <|.. MallardQuack
class MallardSwim {
  swim() : void
}
SwimBehavior <|.. MallardSwim
class MiniDuckSimulator {
  main(args : String[]) : void
}
interface QuackBehavior {
  quack() : void
}
class RubberDuck {
  display() : void
}
Duck <|-- RubberDuck
class RubberFly {
  fly() : void
}
FlyBehavior <|.. RubberFly
class RubberQuack {
  quack() : void
}
QuackBehavior <|.. RubberQuack
class RubberSwim {
  swim() : void
}
SwimBehavior <|.. RubberSwim
class SAFly {
  fly() : void
}
FlyBehavior <|.. SAFly
class SanAntonioDuck {
  display() : void
}
Duck <|-- SanAntonioDuck
class SAQuack {
  quack() : void
}
QuackBehavior <|.. SAQuack
class SASwim {
  swim() : void
}
SwimBehavior <|.. SASwim
class SAWalk {
  walk() : void
}
WalkBehavior <|.. SAWalk
interface SwimBehavior {
  swim() : void
}
interface WalkBehavior {
  walk() : void
}
Duck --> FlyBehavior
Duck --> QuackBehavior
Duck --> SwimBehavior
Duck --> WalkBehavior
@enduml
